// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADnN9IGQxQ-ISZIOAVLY1RskTGwMoEZBA',
    appId: '1:916031725861:web:767e70f5e42c3053703acc',
    messagingSenderId: '916031725861',
    projectId: 'medicinalplantsidentifier',
    authDomain: 'medicinalplantsidentifier.firebaseapp.com',
    storageBucket: 'medicinalplantsidentifier.appspot.com',
    measurementId: 'G-YCL0R1Q967',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMTzJqJ_75iWfp52F7SswdwdV29TfDjI',
    appId: '1:916031725861:android:aa786c36b854afc7703acc',
    messagingSenderId: '916031725861',
    projectId: 'medicinalplantsidentifier',
    storageBucket: 'medicinalplantsidentifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7hsaQtlfc7jE4fUfoeVW32ofbyqmbwMI',
    appId: '1:916031725861:ios:482da49867ebda76703acc',
    messagingSenderId: '916031725861',
    projectId: 'medicinalplantsidentifier',
    storageBucket: 'medicinalplantsidentifier.appspot.com',
    iosClientId: '916031725861-ddok39ijrfqth8n07gv96b6sr3q6hots.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
